### ISSUE TITLE
Improve find by other fields besides the eateries’ name

### ISSUE THREAD

**Issue by debwy** [AY2223S1-CS2103T-W11-1/tp#56]
As a user I can filter food by tags so that I can see only the options that suit my preferences.
As a user I can filter food stalls by location so that I can choose food from a certain area to eat.
As a user I can filter food stalls by cuisine so that I can choose food from a certain cuisine to eat.

**Comment by charleslimjh** [comment]
Ideally, merge the separate find commands into one simple command and facilitate cross-field searches.

We need to support 

- [ ] for name
- [ ] `-l` for location
- [ ] `-t` for tags
- [ ] `-c` for cuisine (to be implemented soon!)
- [ ] `-p` for price (to be implemented soon!)
